version: "3"

tasks:
  build-demo-image:
    desc: "Build the demos image"
    cmds:
      - docker build -f demos/Dockerfile --no-cache . -t shanti-demo:latest

  shell-demo-image:
    desc: "Open shell in the demos container"
    cmds:
      - docker run -v .:/shanti --entrypoint bash -it shanti-demo:latest

  generate-gif:
    desc: "Run vhs on tape file to generate gif. Pass the path for the .tape file"
    cmds:
      - docker run -v .:/shanti -w /shanti/demos/ -it shanti-demo:latest
        {{.CLI_ARGS}}

  setup-demo-env:
    desc: "Setup the demo directories"
    dir: ./demos/
    cmd: |-
      test -d repos-dir || mkdir repos-dir
      pushd repos-dir
      rm -rf *

      for demo_repo in first-repo second-repo
      do
        git clone git@github.com:muzomer/${demo_repo}.git
      done
      popd
      test -d worktrees-dir && rm -rf worktrees-dir
      mkdir worktrees-dir

  create-demo:
    desc: "Command to execute demo from the demos directory"
    dir: ./demos/
    deps:
      - setup-demo-env
    cmd: vhs features.tape
