version: "3"

tasks:
  build-demo-image:
    desc: "Build the demos image"
    cmds:
      - docker build -f demos/Dockerfile --no-cache . -t devspace-demo:latest

  shell-demo-image:
    desc: "Open shell in the demos container"
    cmds:
      - docker run -v .:/devspace --entrypoint bash -it devspace-demo:latest

  generate-gif:
    desc: "Run vhs on tape file to generate gif. Pass the path for the .tape file"
    cmds:
      - docker run -v .:/devspace -w /devspace/demos/ -it devspace-demo:latest {{.CLI_ARGS}}

  setup-demo-env:
    desc: "Setup the demo directories"
    cmd: |-
      test -d demos/repos-dir || mkdir demos/repos-dir
      pushd demos/repos-dir
      rm -rvf *

      for demo_repo in first-repo second-repo
      do
        git clone git@github.com:muzomer/${demo_repo}.git
      done
      popd
      test -d demos/worktrees-dir && rm -rvf demos/worktrees-dir
      mkdir demos/worktrees-dir

  run-demo:
    desc: "Command to execute demo from the demos directory"
    dir: ./demos/
    deps:
      - setup-demo-env
    cmd: vhs {{.CLI_ARGS}}
